### ISSUE TITLE
Let's get a chat room!

### ISSUE THREAD

**Issue by 21cDawn** [plouc/mozaik#10]
This is awesome, saw it from daily.js email list!

I was digging around to see if I had to build it from scratch, and I'm glad I found this place! Bonus it's in my favorite languages, react and node.js.

We need an IRC or something! Where do you guys currently chat?

**Comment by plouc** [comment]
Hi,
Thank you, I'm pleased to know this tool can be useful to someone.
Unfortunately, I don't really chat, sorry.

**Comment by 21cDawn** [comment]
So then this is a project about you, not it's users. gotcha.

"just another dev who doesn’t get the purpose of open source in society"
"move on; fork at will...."

**Comment by 21cDawn** [comment]
That said: I want to see this project succeed, and you are it's captain. I beg you reconsider.
