### ISSUE TITLE
can mozaik support reorder and resize? 

### ISSUE THREAD

**Issue by wangtun** [plouc/mozaik#100]

**Comment by juhamust** [comment]
Based on my experience (http://dashing.io/) reordering and resizing can be tricky at times, whereas explicit model support by Mozaik works always. 

Having said that, I'm not against the feature (as long as it is not the only way to arrange and size the widgets).

**Comment by plouc** [comment]
@wangtun, as @juhamust said, Mozaïk only supports explicit sizing/ordering for now.

**Comment by wangtun** [comment]
@juhamust @plouc thank you very much!
