### ISSUE TITLE
Any way to add a custom stylesheet?

### ISSUE THREAD

**Issue by tomav** [plouc/mozaik#101]
Hi @plouc, just a general question.
I'd like to use http://fizzed.com/oss/font-mfizz on my dashboard.
Is there a simple way to inject je CSS file?

What do you suggest?

Thank you.

**Comment by plouc** [comment]
@tomav, unfortunately, Mozaïk v1 doesn't provide a way to simply add css/fonts, Mozaïk v2 [is on its way](https://github.com/plouc/mozaik/tree/v2.x) and will allow this by simply import the resource from the main app.

**Comment by plouc** [comment]
BTW it seems that [font-awesome](http://fontawesome.io/icons/) which is included by default provides similar icons.

**Comment by plouc** [comment]
And if you want *transitionable* svg icons, you should have a look at [this](http://plouc.github.io/react-svg-buttons/) :)

**Comment by tomav** [comment]
I was looking for icons per programming languages, not bundled in FA default set.
Thanks anyway, I'll have a look to Mozaik 2. I was working on a basic NewRelic extension but will probably postpone to make it work later with Mozaik 2.

**Comment by juhamust** [comment]
My approach would be to create a custom theme.
