### ISSUE TITLE
how long update react

### ISSUE THREAD

**Issue by liwanchong04719** [plouc/mozaik#102]
i try to update react from 0.13.3 to 0.15.1, my program can't work .how long update the react

**Comment by plouc** [comment]
@liwanchong04719 I'm [currently working on Mozaïk 2](https://github.com/plouc/mozaik/tree/v2.x) which support recent version of React, I hope to ship it in september, so please be patient…

**Comment by plouc** [comment]
@liwanchong04719, Mozaïk v2 comes with React 15, see installation instructions [here](http://mozaik.rocks/v2/use/).
