### ISSUE TITLE
What is the right way to develop components in Mozaik?

### ISSUE THREAD

**Issue by jhovgaard** [plouc/mozaik#107]
I'm struggling to figure out how to correctly develop in Mozaik. Right now I'm running `gulp build` and also manually restarting `npm start`, but it's very cumbersome.

Are there any guidelines?

Thanks for an amazing product!

**Comment by plouc** [comment]
@jhovgaard, I agree, it's cumbersome… I'm working on Mozaik 2, which will improve the workflow (using webpack/hotreload/yaml based watched config), but it's a [work in progress](https://github.com/plouc/mozaik/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Moza%C3%AFk+V2%22).

**Comment by plouc** [comment]
If you're brave you can use the v2, https://github.com/plouc/mozaik-demo/tree/mozaik-2, all you have to do is start the devServer `node devServer.js` and the regular backend server `npm start`.

**Comment by plouc** [comment]
You also can use `gulp watch` with v1

**Comment by jhovgaard** [comment]
Thanks for the quick answer!

I was brave (v2) but I instantly got stuck with:

  ```
Html Webpack Plugin:
  TypeError: ReactHotAPI is not a function
  
  - react.js?:1 eval
    C:\code\mozaik-demo/~/react/react.js?:1:317
  
  - react.js?:1 Object.eval
    C:\code\mozaik-demo/~/react/react.js?:1:414
  
  - react.js?:8 eval
    C:\code\mozaik-demo/~/react/react.js?:8:30
  
  - index.html:621 Object.
    [mozaik-demo]/[mozaik]/src/index.html:621:2
  
  - index.html:519 __webpack_require__
    [mozaik-demo]/[mozaik]/src/index.html:519:30
  
  - index.html:50 fn
    [mozaik-demo]/[mozaik]/src/index.html:50:20
  
  - ExecutionEnvironment.js?:1 eval
    C:\code\mozaik-demo/~/fbjs/lib/ExecutionEnvironment.js?:1:231
  
  - ExecutionEnvironment.js?:1 Object.eval
    C:\code\mozaik-demo/~/fbjs/lib/ExecutionEnvironment.js?:1:414
  
  - ExecutionEnvironment.js?:40 eval
    C:\code\mozaik-demo/~/fbjs/lib/ExecutionEnvironment.js?:40:30
  
  - index.html:615 Object.
    [mozaik-demo]/[mozaik]/src/index.html:615:2
  
```
Any help? :-)

**Comment by plouc** [comment]
Which Node/npm versions are you using?

**Comment by jhovgaard** [comment]
Node v6.6.0
npm 3.10.8

**Comment by plouc** [comment]
@jhovgaard, it seems to be an issue with react-hot-loader, unfortunately I'm not able to reproduce it on OSX.

I'll try to use latest react-hot-loader but it requires some config changes.

**Comment by plouc** [comment]
For now, it seems complicated to upgrade, this is a beta release and it lacks of documentation…

**Comment by plouc** [comment]
@jhovgaard, I've tried another approach (restricting include for the webpack js loader).
Can you re-pull the demo (v2) and re-install (I think you can rm node_modules before) ?

**Comment by jhovgaard** [comment]
@plouc that changed the result. 

localhost:8081 throws an exception:
http://i.imgur.com/0xvuDOh.png

Looks like browserify not kicking in or something,

localhost:5000 is returning `Cannot GET /`

**Comment by plouc** [comment]
Where is your extension code/what's the name of the directory ?
The rule for inclusion (babel…) is defined [here](https://github.com/plouc/mozaik/blob/v2.x/webpack.config.js#L55), your extension directory should be named `mozaik-ext-whatever`.

**Comment by jhovgaard** [comment]
It's a completely fresh clone. No custom extensions added.

**Comment by plouc** [comment]
I think it has something to do with the regex and the windows path separator.

You should try to change the regex in `node_modules/mozaik/webpack.config.js` line 59.

**Comment by jhovgaard** [comment]
It worked perfectly, thanks! :-)

**Comment by plouc** [comment]
I'm glad to hear it and thank you for the PR.
