### ISSUE TITLE
error: weather.apiToken: must be of type String

### ISSUE THREAD

**Issue by martyca** [plouc/mozaik#109]
followed the instructions on mozaik.rocks.
cloned repo, check
npm install, check
gulp build, check
node app.js, fail

i get:
info: registered API 'mozaik' (mode: poll)
info: registered API 'github' (mode: poll)
info: registered API 'travis' (mode: poll)
error: weather.apiToken: must be of type String

node version: 6.7.0
npm version: 3.10.3

OS mac-osx

**Comment by contolini** [comment]
The [weather widget](https://github.com/plouc/mozaik-ext-weather#parameters) requires an [openweathermap API key](https://openweathermap.org/appid). You can add it to your dashboard's config.js file or simply define it before starting the app (i.e. `export WEATHER_API_TOKEN=XXXXXXXXXXX`).

**Comment by plouc** [comment]
@martyca, @contolini is right.
When I first developed this extension, the API didn't required an API token.

**Comment by ammmze** [comment]
Might be a good idea to update the usage demo (http://mozaik.rocks/usage/) ;)

Running through the steps on there give this error.

I got it working with `export WEATHER_API_TOKEN=XXXXXXXXXXX && node app.js`. Obviously the token is invalid, but at least gets past the string check to allow it to start up and can play with the demo.
