### ISSUE TITLE
How to use mozaik-ext-value widget / enable more logging to stdout/stderr?

### ISSUE THREAD

**Issue by wojciiii** [plouc/mozaik#111]
I'm trying to use mozaik-ext-value widget with the demo from https://github.com/plouc/mozaik-demo.

My App.jsx:

`import React   from 'react';
import Mozaik  from 'mozaik/browser';
import github  from 'mozaik-ext-github';
import travis  from 'mozaik-ext-travis';
import time    from 'mozaik-ext-time';
import weather from 'mozaik-ext-weather';
import extvalue from 'mozaik-ext-value';

const MozaikComponent = Mozaik.Component.Mozaik;
const ConfigActions   = Mozaik.Actions.Config;

Mozaik.Registry.addExtensions({
    github,
    travis,
    time,
    weather,
    extvalue
});

React.render(<MozaikComponent/>, document.getElementById('mozaik'));

ConfigActions.loadConfig();
`

My server.js

`import Mozaik  from 'mozaik';
import config  from '../config';
import github  from 'mozaik-ext-github/client';
import travis  from 'mozaik-ext-travis/client';
import weather from 'mozaik-ext-weather/client';
import extvalue from 'mozaik-ext-value/client';

const mozaik = new Mozaik(config);

mozaik.bus.registerApi('github',  github);
mozaik.bus.registerApi('travis',  travis);
mozaik.bus.registerApi('weather', weather);
mozaik.bus.registerApi('value', extvalue);

mozaik.startServer();
`

My config contains:

`widgets: [
                {
                    type: 'value',
                    title: 'Test Title',
                    url: 'http://192.168.0.2:8080/stats',
                    columns: 1, rows: 1,
                    x: 2, y: 0
                },
`

This does not work as in no output from any widgets is produced. Also there are no errors to stdout/stderr.
It this simply because of waiting for network? 

How do you debug these issues using mozaik?

**Comment by plouc** [comment]
@wojciiii, I don't know how mozaik-ext-value works internally, but just looking at the client's code, it seems it does not provides logs.

**Comment by plouc** [comment]
And I just noticed you have renamed the extension when registering it:

``` javascript
Mozaik.Registry.addExtensions({
    github,
    travis,
    time, 
    weather,
    value, // not extvalue
});
```

And the type should be `value.value` (https://github.com/arildwtv/mozaik-ext-value/blob/master/README.md).

**Comment by wojciiii** [comment]
Thanks. I will try to use this again with your comments. :)

My problem was more that I was unable to get any indication about what is wrong from the output when I ran "node app".

**Comment by plouc** [comment]
@wojciiii, because in fact nothing is *wrong* on the server side, your component is unknown by the frontend, so it doesn't call the backend, that's why you don't have any log, but I think you should have a log in your browser console saying the component does not exist.

**Comment by wojciiii** [comment]
Ah. Stupid me. I was expecting some kind of timeout in the shell from which I executed node and I did'nt look in the browser. Thanks. :)
