### ISSUE TITLE
V2: Cannot return array as data from server

### ISSUE THREAD

**Issue by glenjamin** [plouc/mozaik#120]
Hi there,

I'm trying out mozaik as I was after a React/Node.js alternative to smashing, it's looking good so far. I'm pretty familiar with webpack HMR, redux etc so I figured I'd have a go with v2.

I ran into a slightly surprising issue, which took a while to track down - API endpoints can't return arrays.

This seems to be because the state uses `.merge` on the API response into an immutable object - is there a reason this is merged rather than `.set`?

**Comment by plouc** [comment]
@glenjamin, sorry for the late reply, you're right, I'll use `.setIn()` instead, currently working on it.

**Comment by plouc** [comment]
Fixed with https://github.com/plouc/mozaik/commit/f098537fd43c5093a2c31270dfce09890934b383
