### ISSUE TITLE
Enable notifications for widgets

### ISSUE THREAD

**Issue by EmrysMyrddin** [plouc/mozaik#121]
There is a notification system already in place. It could be useful for widgets having the possibility to send notifications.

It can be as simple as giving notification actions as props to widgets components ?

**Comment by plouc** [comment]
@EmrysMyrddin, notification system is available for *system wide* notifications, what use case are you trying to cover ?

**Comment by EmrysMyrddin** [comment]
For example, it could be great to notify the user in case of error ?
Or to allow a widget to make an alert.

I'm not using dashboards for BI or monitoring but for information display in my company workspace. And some of my widget could throw some alert sometime (A build failed in production ! for example).

**Comment by plouc** [comment]
You can use the notification system, for example:

```javascript
dispatch(
    notifyError({
        message: `An error occurred while fetching configuration: ${err.message}`,
        ttl: -1,
    })
)
```
