### ISSUE TITLE
v2 settings import is the wrong case

### ISSUE THREAD

**Issue by muffinresearch** [plouc/mozaik#123]
V2 Builds under a case-sensitive OS break because the `settings` import is incorrectly cased. 

Here's the patch required to fix it: https://github.com/muffinresearch/mozaik/commit/c07df8469c19a2ef2567f0ce93ad44634db33e7a

This also sounds like it might be a useful tool for preventing similar issues: https://github.com/Urthen/case-sensitive-paths-webpack-plugin

**Comment by plouc** [comment]
I'm switching from manual react setup for demo to create-react-app for easier setup, which [include this plugin](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/package.json#L31).
