### ISSUE TITLE
V1 gulp build failure

### ISSUE THREAD

**Issue by pachibadilla-scmspain** [plouc/mozaik#124]
Hi,
I've installed v1 but in package json it misses 'npm run build' task :-(

When I load 'gulp build' it showes me an error:

gulp build
 Using gulpfile ~/vagrant/projects/mozaik-demo/mozaik/gulpfile.js
 Starting 'copy:fonts'...
 Copying fonts
 Starting 'copy:styles'...
 Copying styles
 Starting 'copy:imgs'...
 Copying images from extensions and themes
 Starting 'collect:styles'...
 Collecting extensions styles
 Finished 'collect:styles' after 5.17 ms
 Starting 'styles:dev'...
 Starting 'js'...
 'styles:dev' errored after 44 ms
 Error: Cannot find module '/Users/pachi.badilla/vagrant/projects/mozaik-demo/mozaik/config.js' 
  ....

What I'm doing wrong?

Thanks

**Comment by plouc** [comment]
As the last line says, you must have a config file named `config.js`

**Comment by pachibadilla-scmspain** [comment]
OK, I've added a config.js file but there's another error >
Cannot find module '/Users/pachi.badilla/vagrant/projects/mozaik-demo/mozaik/src/App.jsx'

Ok, so I relaunch it build npm task....oh...."npm run build" >
npm ERR! missing script: build

:-(

 I don't see it on repository. Sorry.

**Comment by plouc** [comment]
Please can you provide info about your OS, Node.js/nom version mozaik version & mozaik-demo commit ?

**Comment by pachibadilla-scmspain** [comment]
Yes, of course.

OS > macOS 10.12.5 (16F73) SIerra
Node version > v7.8.0
nvm version > 0.33.1
mozaik-demo version > 1.4.4

Anything else?

Thanks a lot.
