### ISSUE TITLE
Possible to manually change dashboard panel?

### ISSUE THREAD

**Issue by CallumBrankin** [plouc/mozaik#126]
Is it possible to manually change dashboard panel on button click or event?

**Comment by plouc** [comment]
Not in v1, but in v2 you've got a player

<img width="246" alt="capture d ecran 2017-08-23 a 19 30 59" src="https://user-images.githubusercontent.com/501642/29611725-a72e10d8-8839-11e7-9e02-6b5693fd6af5.png">

**Comment by CallumBrankin** [comment]
Is the player an extension? if so where can i find the source code?

**Comment by plouc** [comment]
Not an extension, it's part of `@mozaik/ui` package, source code for the component is available [here](https://github.com/plouc/mozaik/blob/v2.x/packages/ui/src/components/dashboard/DashboardPlayer.js).
