### ISSUE TITLE
[v2] apisPollInterval ignored

### ISSUE THREAD

**Issue by apognu** [plouc/mozaik#128]
Hi,

It seems that the ```apisPollInterval``` directive from my configuration file is ignored, APIs are polled every 15 seconds (the fallback value, I believe).

I tested both ```v2.0.0-alpha.4``` from NPM and ```v2.0.0-alpha.7``` from the git tag and have the same behavior.

15 seconds is really too short for some of my APIs that have to crunch a lot of data.

Also, is there a way to specify a poll interval per API / method?

Thanks.

**Comment by vagnervst** [comment]
Same problem here. Did you find any solution?

**Comment by plouc** [comment]
@apognu I'll have to investigate on this, for the per API interval, I would like to add it but it require a little bit of work :)

**Comment by plouc** [comment]
will be fixed by https://github.com/plouc/mozaik/pull/159

**Comment by plouc** [comment]
fixed by https://github.com/plouc/mozaik/pull/159

**Comment by plouc** [comment]
please note that it must be defined this way:

```yaml
# config.yml
apis:
    pollInterval: 1000
```
