### ISSUE TITLE
Is it possible to load different configurations depending on the environment (V1)?

### ISSUE THREAD

**Issue by CallumBrankin** [plouc/mozaik#131]
Currently i'm trying to use environment variables to load different configurations depending on what environment it is in. For example if i set 'development', it'll load the dev config. If i set 'production' it'll load the production config.

Is this possible?

**Comment by juhamust** [comment]
It is a JavaScript file, so one can do all kind of logic there. I've used this approach:
```javascript
// config.js
module.exports = {
    env: process.env.NODE_ENV || 'production',
    host: process.env.LISTEN_HOST || '0.0.0.0',
    port: process.env.LISTEN_PORT || process.env.PORT || 5000,
    ...
}
```
But nothing prevents you from doing stuff like:
```javascript
const devConfig = {};
const prodConfig = {};
module.exports = process.env.NODE_ENV === 'production' ? prodConfig : devConfig;
```

**Comment by plouc** [comment]
@juhamust, thank you :) @CallumBrankin, did you achieved what you wanted?

**Comment by plouc** [comment]
I close this issue as I got no update on it, hoping you succeeded.
