### ISSUE TITLE
Get API Data as state

### ISSUE THREAD

**Issue by vagnervst** [plouc/mozaik#132]
Hello! I'm trying to implement a real time data filtering on one of my Widgets, but in order to do that, I need to set the data as a state. The problem is: the data is only available at `render()` method, and if I call `setState()` from there, React will end up in a infinite loop. Is there a `onApiData()` handler, or alternative I can use? =)

Thanks!

**Comment by plouc** [comment]
Hi, Maybe you should use [`componentWillReceiveProps`](https://reactjs.org/docs/react-component.html#componentwillreceiveprops) for this.

**Comment by vagnervst** [comment]
@plouc Using `componentWillReceiveProps` I was able to create a state and prevent the bus from updating my data when the filter was applied. Thanks!
