### ISSUE TITLE
How to make it draggable?

### ISSUE THREAD

**Issue by JafferWilson** [plouc/mozaik#133]
I want to know how I can make the widgets draggable and display as per my visual? Say for example Grafana.com. They have the draggable functionality.
Kindly, let me know  your views soon.

**Comment by Immortalin** [comment]
@plouc it's a pretty important feature, most other dashboard libraries have it

**Comment by juhamust** [comment]
I personally like the explicit approach, where you define the order and placements in the code instead of trying to fight with the draggable grid where the grid/system tends to guess the my intentions often wrong :(

**Comment by plouc** [comment]
I'm not planning to add this kind of functionality, Mozaïk isn't the same tool as grafana or kibana (and has way less resources than the teams/companies behind those products :)), those tool were built to allow data exploration while Mozaïk provide a way to give a predefined view of your data.
