### ISSUE TITLE
[v2] Allow api `mode` to be set

### ISSUE THREAD

**Issue by sanderpick** [plouc/mozaik#148]
Awesome library! Just started playing around with it. Probably intentional, but curious why [`Mozaik.registerApi`](https://github.com/plouc/mozaik/blob/v2.x/packages/server/src/index.js#L116) aliased to `Bus.registerApi` doesn't allow setting `mode`? `bus` isn't exported, so, it doesn't seem like there's currently a way to register a `push` api, could be missing something though.

**Comment by plouc** [comment]
`registerApi` is now a pure alias, see https://github.com/plouc/mozaik/blob/master/packages/server/src/index.js#L112
