### ISSUE TITLE
user dashboard

### ISSUE THREAD

**Issue by ktamilvanan** [plouc/mozaik#155]
I am looking to use mozaik to provide dashboard a based on the logged in user. What is the right way to achieve this functionality? Can the server be updated with multiple user's dashboard and client be specific to the logged in user?

**Comment by juhamust** [comment]
You _might_ be able to achieve the wanted functionality by authenticating the user and then using the current user identifier to fetch the correct content in each client.

https://github.com/plouc/mozaik/issues/117

**Comment by plouc** [comment]
Mozaïk doesn't support this out of the box, and I'm not planning to add this for now, you might be able to achieve this by using the approach suggested by @juhamust however you won't benefit from existing extensions, so I'm not sure Mozaïk is the right tool for your use case.
