### ISSUE TITLE
Check the render method of `WidgetHeader`. For Mozaik V2

### ISSUE THREAD

**Issue by sshaginyan** [plouc/mozaik#164]
So I ran npm start and node server.js and got this error message.

![screen shot 2018-10-04 at 9 04 59 pm](https://user-images.githubusercontent.com/325014/46515536-37c20580-c819-11e8-8604-86b589d79957.png)

proxyConsole.js:56 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `WidgetHeader`.
    in WidgetHeader (created by WithTheme(WidgetHeader))
    in WithTheme(WidgetHeader) (created by Inspector)
    in div (created by styled.div)
    in styled.div (created by Widget)
    in div (created by styled.div)
    in styled.div (created by Widget)
    in Widget (created by Inspector)
    in Inspector (created by WidgetWrapper)
    in WidgetWrapper (created by WithTheme(WidgetWrapper))
    in WithTheme(WidgetWrapper) (created by Connect(WithTheme(WidgetWrapper)))
    in Connect(WithTheme(WidgetWrapper)) (created by TransitionMotion)
    in div (created by TransitionMotion)
    in div (created by styled.div)
    in styled.div (created by TransitionMotion)
    in TransitionMotion (created by Dashboard)
    in Dashboard (created by Mozaik)
    in div (created by styled.div)
    in styled.div (created by Mozaik)
    in Mozaik (created by Connect(Mozaik))
    in Connect(Mozaik) (created by MozaikWrapper)
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (created by Connect(ThemeProvider))
    in Connect(ThemeProvider) (created by MozaikWrapper)
    in Provider (created by MozaikWrapper)
    in MozaikWrapper (at index.js:7)

**Comment by delikatessa** [comment]
check issues in mozaik-demo repo, e.g. https://github.com/plouc/mozaik-demo/issues/17

**Comment by alexcurtin** [comment]
same issue, don't see it referenced in mozaik-demo issues

**Comment by alexcurtin** [comment]
@delikatessa Can you help me get v2 working locally? the instructions aren't working and even after patching it I run into the issue above, any help would be appreciated thanks!

**Comment by alexcurtin** [comment]
bump

**Comment by plouc** [comment]
Yes, v2 requires a newer version of `react` & `react-dom`, https://github.com/plouc/mozaik/blob/master/packages/ui/package.json#L31
