### ISSUE TITLE
[Enhancement] Keyboard support to switch dashboards (space, left, right)

### ISSUE THREAD

**Issue by przemuh** [plouc/mozaik#168]
On my team dashboard-tv I needed to hide all headers from mozaik to get more space for widgets. I have three screens with 15s duration.

It would be nice if I could pause duration via SPACE key. Moreover it would be nice to have the possibility to go to the next/prev screen via LEFT/RIGHT ARROW key.

@plouc what do you think? I would love to implement this and make a pull request. But first I wanted to ask you about this feature enhancement.

**Comment by plouc** [comment]
@przemuh, good idea! It could be a great addition
