### ISSUE TITLE
[Enhancement] Serve multiple dashboards based on config file

### ISSUE THREAD

**Issue by przemuh** [plouc/mozaik#169]
Instead of serving one page on root path `/` it would be nice to serve proper dashboard based on config name in path.

Example folders/files:
```
config/config1.yaml
config/config2.yaml
config/temp.yaml
```

Router paths:
```
localhost:8080/dashboard/config1  // serves dashboard based on config1.yaml
localhost:8080/dashboard/config2  // serves dashboard based on config2.yaml
localhost:8080/dashboard/temp    // serves dashboard based on temp.yaml
```

@plouc what do you think ?

**Comment by plouc** [comment]
Supporting this would require heavy changes on both the UI and the server, and Mozaïk already supports the configuration of several dashboards inside a single config file.
