### ISSUE TITLE
Navigation between dashboards

### ISSUE THREAD

**Issue by VikramTantravahi** [plouc/mozaik#171]
I am looking for navigation between these dashboards like via `on-click` versions and also saving the displayed data to backend databases. Anyone worked on anything similar? 
Would be open to discuss.

**Comment by plouc** [comment]
There's already a navigation available in v2 in the top bar.

**Comment by plouc** [comment]
However nivo doesn't handle the data storage, you'll have to put something in the middle.

**Comment by VikramTantravahi** [comment]
Oh thanks for the quick response. 
I'll try out V2, but I am mostly using and customizing `mozaik-ext-jenkins` which still seems to be compatible only for V1.
