### ISSUE TITLE
Add gitlab widgets

### ISSUE THREAD

**Issue by plouc** [plouc/mozaik#2]

**Comment by jhawlwut** [comment]
any progress on this? we're curious about using mozaik / gitlab, but before we go and write our own plugin, wanted to make sure the core wasn't going to updated with this soon...

**Comment by plouc** [comment]
@jhawlwut, it was a proposal and for now I didn't planned to work on it, but I'll be very glad if you work on a custom gitlab mozaïk extension!
To get started with extension development, I think you should take a look at the [mozaik-ext-github](https://github.com/plouc/mozaik-ext-github) repo as it's one of the most complete one and the API is very similar to gitlab's one.
If you have some questions or need help, do not hesitate to ask on [gitter](https://gitter.im/plouc/mozaik).

**Comment by plouc** [comment]
@jhawlwut, I close this issue, did you stared something with gitlab, I'll be glad to help if you did ?
