### ISSUE TITLE
Add support for loading widgets from external modules

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik#20]
Provide an easy way to develop, publish and install new widgets as separate npm modules. 

Also, it should be possible to install Mozaïk as dependency while having dashboard config and related resources (like theme?) maintained in own repository.

**Comment by juhamust** [comment]
Some food for thought and motivation:

I've been using both [Dashing](http://dashing.io/) and [Atlasboard](https://bitbucket.org/atlassian/atlasboard/) to build dashboards and they both fall short with extending/contributing. 

- Atlasboard uses git submodules that is less ideal and makes it next to impossible to bring own resources and dependencies into play. [Outcome is quite rigid](https://bitbucket.org/atlassian/atlasboard/issues?status=new&status=open)
- Dashing uses gists, but it's quite manual process and does not version well.
- There are some projects, like [dashing-contrib](https://github.com/QubitProducts/dashing-contrib/) that tries to improve the situation, but I feel the best way is to [manage each widget/theme/whatever as a separate](https://github.com/QubitProducts/dashing-contrib/issues/7) repo+npm module.

Some ideas & wishes:

- Provide a way to access dashboard logger
- Allow a widget to introduce new dependencies (each have their own package.json)
- Dashboard could provide a storage (persistent or not) that widgets could utilise to cache some data
- Provide a way to add new middleware to server, for example for authentication

----

This project has a great potential, and if you manage to bring good extendability to it, that'll greatly help people to contribute.

**Comment by plouc** [comment]
@juhamust thanks for the feedback, I'm currently working on making the extensions npm modules and plan to make the express app available for customization, but for now I don't plan to introduce a storage layer, but because the extensions will now be able to declare their own dependencies, it's possible to add it for a specific extension. I've also added the winston logger, I must find a clean way to expose it.
If you're curious, there is a PR in progress here plouc/mozaik/pull/23 and I've already published (really beta) modules to npm https://www.npmjs.com/search?q=mozaik

**Comment by juhamust** [comment]
This is excellent news! I will try out the branch in near future, but sounds good.

If you'll find winston logger too limited at some point, I recommend trying [bunyan](https://www.npmjs.com/package/bunyan) as an alternative.

**Comment by juhamust** [comment]
Thanks for the update @plouc! Sure it's a big effort (causing some regressions and whatnot), but I believe it will greatly help people to contribute/extend in the long run.

You may also need to give up with wiki powered extension documentation and encourage widget author using README.(md/rst) instead. Maybe even provide a `mozaik-ext-boilerplate`?

**Comment by plouc** [comment]
I've published mozaik and mozaik-ext-* npm modules but I have to update the whole wiki because of the switch and add more tests on it.
I'm thinking of a yeoman generator for the extension boilerplate.

**Comment by juhamust** [comment]
Any plans for merging this to `master` branch soon? It also seems that there is some code pushed to npmjs that does not exist in version control yet (for example Mozaik.loadApiConfig) - which makes a bit more challenging to use version control as dependency for time being.

**Comment by plouc** [comment]
Yes, I'm sorry for that, as it's a side project I didn't had enough time to dry the *extensibility* branch, by the way, I'll try to push code released on npm asap.

**Comment by plouc** [comment]
The extensibility branch is now up to date with the latest npm package

**Comment by juhamust** [comment]
Great, thanks.

**Comment by plouc** [comment]
@juhamust, I've merged the `extensibility` branch and I'm currently working on yeoman generators for custom dashboard and extension, see https://github.com/plouc/mozaik-generator.

I have not yet updated the wiki.

**Comment by juhamust** [comment]
Excellent work, @plouc. I've got couple of widgets already cooking up, and while being developed on work-time, hoping to release them under permissive license soon.

**Comment by juhamust** [comment]
Feel free to close this ticket.

**Comment by juhamust** [comment]
Putting the money where my mouth is, now there are couple of extensions published:

- https://www.npmjs.com/package/mozaik-ext-analytics
- https://www.npmjs.com/package/mozaik-ext-sheets
