### ISSUE TITLE
Widget instance can be configured only once

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik#21]
Perhaps I'm doing something wrong, but it seems that the one widget type can be configured only once as the second instance gets the same location parameter value despite the config:

config.js
```
{
    type: 'mywidget',
    location: 'foo',
    columns: 1, rows: 1,
    x: 2, y: 0
},
{
    type: 'mywidget',
    location: 'bar',
    columns: 1, rows: 1,
    x: 1, y: 0
},
```

In both cases, the location value is `foo` in params.

**Comment by plouc** [comment]
@juhamust could you please provide your component code ? How do you register your widgets ?

**Comment by juhamust** [comment]
I can, but not that I tested with built-in Weather widget it seems to output correct results (giving different weather info):

```
{
  type: 'weather.weather',
  city: 'Tokyo',
  country: 'JP',
  lang: 'en',
  limit: 2,
  columns: 1, rows: 1,
  x: 3, y: 1
},
{
  type: 'weather.weather',
  city: 'London',
  country: 'UK',
  lang: 'en',
  limit: 2,
  columns: 1, rows: 1,
  x: 0, y: 1
}
```

So I'll check the code once again, but if still fail to succeed and you're willing have another look on it, that would be appreciated.

**Comment by plouc** [comment]
@juhamust did you solved your problem ? if not, don't hesitate to provide your widget code.

**Comment by juhamust** [comment]
Thanks for asking - I now had a time to look at the code again found the issue in `id` within `getApiRequest()`: It was not unique between locations. After including the `location` info into `id`, the issue was fixed.

By the way, that is possibly something to mention in [Extending -section](https://github.com/plouc/mozaik/wiki/Extend), too.
