### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by s-pace** [plouc/mozaik#265]
👋  team,

It seems that the demo available from http://mozaik.herokuapp.com/ is down as you can see on the following screenshot:
![image](https://user-images.githubusercontent.com/32097720/123559483-891a3c00-d79c-11eb-9e27-4d76fe65da00.png)

Keep it up 🚀

**Comment by plouc** [comment]
Hey, I use a free heroku dyno, but most of the time, usage exceeds the free tier at the end of the month, and we end up with this issue. As I don't earn any money with this project, I don't plan to change that, sorry.
