### ISSUE TITLE
Dashboard rotation does not adhere rotationDuration config value

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik#30]
Dashboard rotation is hardcoded to 4000ms: 
https://github.com/plouc/mozaik/blob/extensibility/src/browser/stores/DashboardStore.js#L19

Whereas mozaik-demo hints about the config value: 
https://github.com/plouc/mozaik-demo/blob/master/config.js#L33

**Comment by plouc** [comment]
Fixed with https://github.com/plouc/mozaik/commit/778b36457063d27246f063b1ce7a83c0e11d8c2d

**Comment by juhamust** [comment]
Thanks for the quick turnaround!
