### ISSUE TITLE
Theme is hard coded / add support for providing a custom theme

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik#32]
Theme is hard coded to `night-blue`: https://github.com/plouc/mozaik/blob/master/gulp/tasks/styl.js#L15

While fixing the issue, the support of providing a custom theme could be added as well: In a case the config `theme` variable is *not* a theme name delivered with Mozaik, it is considered as a relative path to theme folder (based on `config.js`)?

**Comment by plouc** [comment]
It's now fixed, but you cannot yet set a custom theme, I have to find a way to give an alternate path, not just a theme name

**Comment by plouc** [comment]
@juhamust you should now be able to use a custom theme, all you have to do is to conform this directory layout:

```
+ /my-dashboard
+—+ /themes
  +—+ /mine
    +— _vars.styl
    +— index.styl
```

Then, you can set theme to `mine` in your config.

**Comment by juhamust** [comment]
Great! Based on quick test, seems to work as expected.
