### ISSUE TITLE
Add support for real-time communication

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik#34]
Current polling model work nicely most of the cases. However, if more accurate data is needed, the approach no longer. Thus, it should be possible for client to communicate with the client whenever needed.

**Example scenario:** Server side client creates a WebSocket or MQTT connection to data source. Whenever a message is received, client communicates it to all the interested widgets.

@plouc: I'm sure you have an idea how to implement this without affecting too much on the API.

**Comment by juhamust** [comment]
This is also related to #4: Once the interval can be defined per backend API, it can be decreased for specific data sources. However, it remains to see how the service will work if interval is only, say 1 second?

**Comment by plouc** [comment]
I think it could be saner to let the backend stream its data to the component, perhaps introducing a subscription type `poll` or `stream|pipe` without breaking the current api (`poll` should be default if none given). I'll try to test this approach.

**Comment by juhamust** [comment]
Sounds good to me. Thanks.

**Comment by juhamust** [comment]
Any progress with this?

**Comment by cybernet** [comment]
any news ?

**Comment by plouc** [comment]
@juhamust, @cybernet done! available in `mozaik@1.3.0`, see https://github.com/plouc/mozaik/pull/76, for now, there's no proper documentation on how to use the feature, I must update http://mozaik.rocks/ accordingly, but I have made a simple gist to explain how to use it https://gist.github.com/plouc/5fc5d80aa74e4a6c3196a265602c509c.

And of course, if you have any feedback/issue with it, just let me know!
