### ISSUE TITLE
"publish" is not in your gulpfile

### ISSUE THREAD

**Issue by himynameisdave** [plouc/mozaik#40]
Installed the mozaik yeoman generator and ran it. Ran into a peerDep issue (unrelated I think) and then I was unable to run `gulp publish` like it says to in the docs.

##### Steps to reproduce:
1. run `yo mozaik` to generate the base files.
2. run `npm i` to install dependencies.
3. Fix the following peerDependency issue by specifying `^0.13.0` for react in the `package.json`: 
![screen shot 2015-07-29 at 11 21 06 am](https://cloud.githubusercontent.com/assets/4298089/8961558/ef809928-35e3-11e5-8f9c-6eddc51cc2f5.png)
4. Run `npm i` again to install that package (I'm lazy & didn't feel like typing out `npm i react@0.13.0` or whatever it is.
5. Run `gulp publish`, as it says to in the docs. Get error:
![screen shot 2015-07-29 at 11 18 40 am](https://cloud.githubusercontent.com/assets/4298089/8961656/77cd693c-35e4-11e5-843e-0df88b4c20db.png)
6. Running the default `gulp` task will run through some tasks, none of which is publish. Attempting to run `node app.js` afterwards results in the following error:
![screen shot 2015-07-29 at 11 28 37 am](https://cloud.githubusercontent.com/assets/4298089/8961744/0315291c-35e5-11e5-92c3-1a5b51be0cbe.png)

##### Tested with:
**node:** 0.10.32 & 0.12.7
**npm**: 1.4.28 & 2.11.3

**Comment by plouc** [comment]
@himynameisdave I've changed a lot of things on mozaïk yesterday, I have to update the generator, I hope I can do it today

**Comment by himynameisdave** [comment]
I was just about to add that it was working fine on Monday! Thanks man (y)

**Comment by himynameisdave** [comment]
Hey unrelated but since you're the key dev on this...
...can you use [mozaik-ext-github](https://github.com/plouc/mozaik-ext-github) with GH Enterprise?

**Comment by plouc** [comment]
@himynameisdave, I think you can, you'll have to set the `baseUrl` pointing to it

**Comment by himynameisdave** [comment]
@plouc thank you! :)

**Comment by plouc** [comment]
@himynameisdave I've updated [mozaik-ext-github](https://github.com/plouc/mozaik-ext-github) readme

**Comment by plouc** [comment]
@himynameisdave you can now update mozaik generator and use `gulp build` instead of `gulp publish` (documentation updated). let me know if it works with the update

**Comment by himynameisdave** [comment]
@plouc thanks, you're the best. That seemed to work great, runs through the generator no problem and the `peerDependency` issues seem to be resolved as well. I guess you could say...

![as planned](http://cdn.memegenerator.net/instances/500x/34240159.jpg)

Closing these issues now.
