### ISSUE TITLE
Wrong positioning of widget content

### ISSUE THREAD

**Issue by xyNNN** [plouc/mozaik#50]
Hey folks,

I have encountered an issue that the widget content isn't centered in the widget body. Can anyone else reproduce this? I think it's because of the absolute positioning from the .widget__body
![bildschirmfoto 2015-11-22 um 11 31 31](https://cloud.githubusercontent.com/assets/1929750/11323199/de39b9a4-910c-11e5-85d0-432b84d1d3b5.png)

**Comment by plouc** [comment]
@xyNNN, this problem is related to mozaik-ext-time widget which is not vertically centered when no title is defined

**Comment by plouc** [comment]
I just saw I already had

**Comment by plouc** [comment]
feel free to re-open if it doesn't solve the issue
