### ISSUE TITLE
How do you handle build of widgets when creating new widget ?

### ISSUE THREAD

**Issue by tlenclos** [plouc/mozaik#52]
Hi and thanks for your work on Mozaik !

Quick question, how do you handle the build of new widgets using ES6 syntax ?
For example I forked your github widget and used `npm link`, then I got an error when starting the app as the ES6 syntax if not valid:
```
/Users/.../mozaik-ext-github/src/client.js:1
(function (exports, require, module, __filename, __dirname) { import request f
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
```

**Comment by plouc** [comment]
You'll have to tell browserify to transpile your module, https://github.com/plouc/mozaik-ext-github/blob/master/package.json#L49

**Comment by tlenclos** [comment]
I'm using `gulp watch` on my mozaik project, `npm link with` my fork of your github widget. So I got the same package.json  that you linked.

**Comment by tlenclos** [comment]
Maybe you can document your workflow when creating a new widget or forking an existing one ?

**Comment by plouc** [comment]
You're right, I could :) Unfortunately, I were not able to make the link npm command works because of peer dependencies, I put the git repo directly into the node_modules directory

**Comment by tlenclos** [comment]
And what command are you doing to compile the files in `node_modules/mozaik-ext-github` for example ?

**Comment by plouc** [comment]
Don't have have my laptop right now, but I think it's:
```
gulp watch:dev
```
BTW, the actual workflow is annoying, I'm planning to move to webpack soon

**Comment by plouc** [comment]
@tlenclos, I'm closing this issue, feel free to create one if it doesn't work

**Comment by torarnv** [comment]
Any update on webpack? I'm looking into using mozaik for our dashboard, as it looks really shiny, but the process of creating a new widget seems a bit complicated, lots of react boilerplate, rebuilding between each code/style change. Is there a recommended workflow that perhaps looks more like the simplicity of dashing, e.g. https://gist.github.com/YuriKazakov/c85f8cbde7235105dd16 ?

**Comment by plouc** [comment]
@torarnv, unfortunately, I don't have the time for now to work on my side projects

**Comment by plouc** [comment]
You should have a look at the [time widgets](https://github.com/plouc/mozaik-ext-time)

**Comment by torarnv** [comment]
@plouc Sorry to hear that, but thanks for being honest! :+1:

**Comment by plouc** [comment]
but the time widget is light enough (with some react boilerplate) :)
