### ISSUE TITLE
Demo page displays a blank canvas

### ISSUE THREAD

**Issue by jottr** [plouc/mozaik#53]
It seems that the demo on heroku does currently not work.

**Comment by plouc** [comment]
@jottr, thanks for the info, but it works for me, can you re-try please ?
Sometimes proxies don't like websockets which, in that case have to be served over ssl/tls, what error message do you get ?

**Comment by jottr** [comment]
The issue seems to be due to some  "ad-blocking" extension.
Sorry for the false alarm.
