### ISSUE TITLE
Demo currently failing

### ISSUE THREAD

**Issue by keithamus** [plouc/mozaik#57]
I get a blank screen on the demo app (https://mozaik.herokuapp.com/).

It seems to be because Chrome doesn't allow cross-protocol websocket access (as in https with ws or http with wss).

```
Mixed Content: The page at 'https://mozaik.herokuapp.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://mozaik.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.r.default.createStore.initWs @ mozaik.min.js:14
```
```
Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

**Comment by plouc** [comment]
@keithamus, the demo doesn't support wss for now, it's configured to use ws only

**Comment by plouc** [comment]
where did you got the https link ? (just to be sure I didn't put an https demo link in the docs)

**Comment by keithamus** [comment]
Ahh, I just twigged that its my [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en) extension - it was auto redirecting the all *.HerokuApp.com sites to their https equivalents. I've disabled it and the dashboard is working now.
