### ISSUE TITLE
Problems using useWssConnection:true

### ISSUE THREAD

**Issue by benediktvaldez** [plouc/mozaik#62]
We are serving the dashboard via https, ofc :smile:, and enabled the `useWssConnection: true` in our config.js, but can't seem to get it working, seeing this error message

```
WebSocket connection to 'wss://dashboard.our-domain.com/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```

Should I be doing something else to get this working?

**Comment by juhamust** [comment]
Are you using somekind of proxy (Nginx, Apache etc.) between? If so, ensure it does handle the websocket connections correctly.

**Comment by benediktvaldez** [comment]
Good catch @juhamust , me being silly..

How about while working on it locally, there I get
```
WebSocket connection to 'wss://localhost:3000/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```
Should I just use `ws` locally and `wss` on the server?

**Comment by juhamust** [comment]
I'd use `ws` while developing, yes.
