### ISSUE TITLE
Document how to use the Inspector, Timer element

### ISSUE THREAD

**Issue by kurtextrem** [plouc/mozaik#87]
Using the Inspector Element is easy:
`{
            columns: 1,
            rows: 1,
            widgets: [{
                type: 'mozaik.inspector'
            }]
        },`
but what about the timer?

**Comment by plouc** [comment]
In fact Timer isn't meant to be used, I'll probably remove it.
You're right about the inspector, feel free to make a PR :)

**Comment by plouc** [comment]
@kurtextrem, removed the timer and added documentation on the `inspector` widget (for [v1](http://mozaik.rocks/v1/use/widgets/) and [v2](http://mozaik.rocks/v2/use/widgets/)).
