### ISSUE TITLE
Jenkins views

### ISSUE THREAD

**Issue by gutobortolozzo** [plouc/mozaik#9]
I would like to suggest one Jenkins Widget to monitor views, Providing information about percentage of time that view spent blue, yellow and green for instance. 

What you think about this idea ? And expand to aggregate other metrics from views ?

**Comment by plouc** [comment]
@gutobortolozzo it could be interesting, I dont' know which data the jenkins API expose for views for now, but I often use the pipeline plugin and the pipeline view is also very interesting. Are you comfortable with react/node, interested in contributing ?

**Comment by plouc** [comment]
@gutobortolozzo I've added a simple jenkins 'view' widget, see https://github.com/plouc/mozaik/wiki/Jenkins-Widgets#jenkins-view

**Comment by gutobortolozzo** [comment]
@plouc, looks really nice. I will try and later I will give you a better feedback.

About the question, "interested in contributing?" Sure, just give me some issue to develop :)
