### ISSUE TITLE
Extension not calling Client function

### ISSUE THREAD

**Issue by sampengilly** [plouc/mozaik#91]
Hi,

I've been trying to modify the Jenkins extension to call the TeamCity API and have run into an issue that I can't seem to debug. My extension is being correctly imported, the API client is being registered: `info: registered API 'teamcity' (mode: poll)` and the widget is being displayed (albeit with a blank body). The widget's `getApiRequest` method is:
```javascript
getApiRequest() {
    console.log('[teamcity] getApiRequest called');
    const { buildType, layout } = this.props;
    
    return {
        id:     `teamcity.buildType.${buildType}`,
        params: { buildType }
    };
}
```
The `ListenerMixin` and `ApiConsumer` mixins are both being applied and the `console.log` is being hit and is outputting correctly. 

The API Client's methods look like:
```javascript
const apiMethods = {
    projects(params) {
        return buildRequest('/httpAuth/app/rest/projects')
            .then(res => res.body.project)
          ;
    },

    buildType(params) {
        mozaik.logger.info('[teamcity] buildType called');
        return buildRequest('/httpAuth/app/rest/buildTypes/id:${ params.buildType }/builds')
            .then(res => res.body.build)
        ;
    },
};

return apiMethods;
```

The log entry in `buildType` is NOT getting called, and the `info: Added subscription: 'teamcity.buildType.myBuildType'` log entry is NOT appearing. Despite the client being correctly registered as seen in the initial registration log.

I've tried stepping through the code and have looked over all the extensions multiple times and can't see anything that I'm doing differently that would cause this. Any help would be much appreciated.

**Comment by gazab** [comment]
I'm not exactly sure what this issue is but have you seen my TeamCity extension here: https://github.com/gazab/mozaik-ext-teamcity? Maybe check it out for some inspiration. And feel free to use it and improve it with pull requests :) 

It's up on npm too and I'm using it myself daily.

**Comment by juhamust** [comment]
Interesting: I'm having same issue with extension of mine. https://gitter.im/plouc/mozaik?at=576509162a4cd63745ea80f4

**Comment by sampengilly** [comment]
@gazab That solves my immediate need for TeamCity integration nicely, thanks!

Since this was also a learning exercise in developing an extension and @juhamust is experiencing the same issue I'll leave this open as a bug or miscommunication in documentation might still exist.

I think for my next extension I'll see if I have any luck starting from scratch if one isn't already available.

**Comment by kurtextrem** [comment]
I had the same issue. I "solved" it with forking mozaik-ext-jenkins, stripping out all the jenkins stuff and renaming all of "jenkins" to something else. It succeeded, but I still don't know why my first try didn't work.

**Comment by plouc** [comment]
I close this issue as the problem seems to have been solved.

**Comment by juhamust** [comment]
For the record, I'm still struggling with the issue and have tried to resolve it every now and then (with limited time given for the subject). I suppose I'd also need to fork existing extension to make it work. Something fishy here, after all I'm working with extension that used to work with older Mozaik.

@plouc Can I expect Mozaik to work with Node 4.x+?

**Comment by plouc** [comment]
@juhamust, have you tried to use node 4 with npm@3 ?

**Comment by plouc** [comment]
BTW, mozaik 2 will only be compatible with Node v6+, because I don't want to use a transpiler while a recent Node version can handle es6 features :)

**Comment by juhamust** [comment]
Most of the time I'm using Node 5.x which comes natively with npm 3(?). Not even sure if I can mix and match different Node and npm when using tools like nvm?

Anyway, if there are no known issues with Node 5.x or Node 6.x with Mozaik 1.x will continue with those.

**Comment by plouc** [comment]
@juhamust you just have to:
```sh
npm i -g npm@3
```
it even works with Node v0.10.x

**Comment by juhamust** [comment]
Ok, I had a yet another look into this: Apparently the issue was the _incorrect Mozaik instance_ in extension `node_modules`:

After running `npm link ../mozaik-demo/node_modules/mozaik` in extension folder, the extension started to work as expected. :+1: 

So, despite the browserify-resolutions, it might be good idea to link _the same React_ and  _Mozaik_ modules one is developing the extension againt. Especially if the outcome is not exactly working as expected.
